config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blog_posts
  #get "/blog_posts/new", to: "blog_posts#new",  as: :new_blog_post
  #get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  #patch "/blog_posts/:id", to: "blog_posts#update"
  #delete "/blog_posts/:id", to: "blog_posts#destroy"
  #get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  #post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title,presence: true
    validates :body,presence: true
    validates :author,presence: true
    validates :tags,presence: true
    validates :comments,presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.all
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :author, :tags, :comments)
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: "You must sign in or sign up to continue" unless user_signed_in?
  end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>
<%= form_with model: @blog_post, local: true do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div>
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div>
    <%= form.submit "Update Blog Post" %>
  </div>
    <%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>
<% @blog_posts.each do |blog_post| %>
  <h2><%= link_to blog_post.title, blog_post %></h2>
  <p><%= blog_post.body %></p>
  <p><%= blog_post.author %></p>
  <p><%= blog_post.tags %></p>
  <p><%= blog_post.comments %></p>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :author %>
    <%= form.text_area :author %>
  </div>
  <div>
    <%= form.label :tags %>
    <%= form.text_area :tags %>
  </div>
  <div>
  <%= form.label :comments %>
  <%= form.text_area :comments %>
</div>
  
    <%= form.submit "Create Blog Post" %>
<% end %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
<h1><%= @blog_post.title %><h1>
<%= @blog_post.body %>
<%= @blog_post.author %>
<%= @blog_post.tags %>
<%= @blog_post.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
      <%= link_to "New blog post", new_blog_post_path %>
        <%#= link_to "profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <%# else %>
        <%#= link_to "Login", new_user_session_path %>
        <%#= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>